# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

na_omitc <- function(x) {
    .Call(`_NPVecchia_na_omitc`, x)
}

thetas_to_priors_c <- function(thetas, n2, thresh = 1e-3) {
    .Call(`_NPVecchia_thetas_to_priors_c`, thetas, n2, thresh)
}

get_posts_c <- function(datum, a, b, g, NNarray) {
    .Call(`_NPVecchia_get_posts_c`, datum, a, b, g, NNarray)
}

samp_posts_c <- function(posts, NNarray) {
    .Call(`_NPVecchia_samp_posts_c`, posts, NNarray)
}

minus_loglikeli_c <- function(thetas, datum, NNarray) {
    .Call(`_NPVecchia_minus_loglikeli_c`, thetas, datum, NNarray)
}

rcpparma_hello_world <- function() {
    .Call(`_NPVecchia_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_NPVecchia_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_NPVecchia_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_NPVecchia_rcpparma_bothproducts`, x)
}

