# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove NAs from a vector
#'
#' This function is needed for the direct translation of the R functions to C++. This function is 
#' taken from StackOverflow approximately: https://stackoverflow.com/questions/19156353/remove-na-values-efficiently
#'
#' @param x a vector (possibly with NAs)
#' 
#' @export
#' @examples
#' na_omit_c(c(NA,5,10,NA,303))
na_omit_c <- function(x) {
    .Call(`_NPVecchia_na_omit_c`, x)
}

#' Transforms hyperparameters to priors
#' 
#' This is the C++ version of \code{\link{thetas_to_priors}}. See there for further documentation.
#' 
#' It is often about the same speed as the R version of this function due to little computational cost.
thetas_to_priors_c <- function(thetas, n, thresh = 1e-3) {
    .Call(`_NPVecchia_thetas_to_priors_c`, thetas, n, thresh)
}

#' Gets posteriors of Bayesian methodology
#' 
#' This is the C++ version of \code{\link{get_posts}}. See there for further documentation.
#' 
get_posts_c <- function(datum, a, b, g, NNarray) {
    .Call(`_NPVecchia_get_posts_c`, datum, a, b, g, NNarray)
}

samp_posts_c <- function(posts, NNarray) {
    .Call(`_NPVecchia_samp_posts_c`, posts, NNarray)
}

minus_loglikeli_c <- function(thetas, datum, NNarray) {
    .Call(`_NPVecchia_minus_loglikeli_c`, thetas, datum, NNarray)
}

rcpparma_hello_world <- function() {
    .Call(`_NPVecchia_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_NPVecchia_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_NPVecchia_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_NPVecchia_rcpparma_bothproducts`, x)
}

